### ISSUE TITLE
[Perf] Add support for resumable zfs receive

### ISSUE THREAD

**Issue by whoschek** [whoschek/bzfs#1]
[Perf] Add support for resumable zfs receive, via zfs receive -s.
Would be nice to have, especially for transferring large snapshots over wireless networks.

**Comment by rptb1** [comment]
I use syncoid to move large changes between systems that sometimes become unreachable, or are rebooted, and so it's quite important that transfers resume.  BZFS looks good, maintainable (Python), and is quick so I look forward to its development!

**Comment by whoschek** [comment]
Agreed. FYI, just In case your situation involves transfering many small snapshots (rather than a single large snapshot), then that already works well today because incremental snapshots that have already transferred as part of the current zfs send/receive won't be retransmitted. In other words, a retry will retry starting with the last failed snapshot, not with the first snapshot.

**Comment by whoschek** [comment]
@rptb1 This is now fixed in the 1.3.0 release. The details are here: https://github.com/whoschek/bzfs/commit/06474b527468bf90349a94ca710fe70a6835c784 
Give that a try.

**Comment by whoschek** [comment]
Fixed in https://github.com/whoschek/bzfs/commit/06474b527468bf90349a94ca710fe70a6835c784
